#!/usr/bin/env bash
# ____        _     _ _              ___  ____
#|  _ \  __ _| |__ | | | _____  ___ / _ \/ ___|     Stefan Dahlke
#| | | |/ _` | '_ \| | |/ / _ \/ __| | | \___ \     https://www.github.com/dahlkes
#| |_| | (_| | | | | |   <  __/\__ \ |_| |___) |
#|____/ \__,_|_| |_|_|_|\_\___||___/\___/|____/
#
# NAME: DahlkesOS
# DESC: A installation script for my personal ArchLinux setup.
# WARNING: Run this script at your own risk.

mkdir archlive
cp -r /usr/share/archiso/configs/releng ./archlive
mv ./archlive/releng ./archlive/dahlkesOS
cp installArch ./archlive/dahlkesOS/airootfs/root/dahlkesOS
mkdir work
sudo mkarchiso -v -w ./work ./archlive/dahlkesOS
rm -r work
rm -r archlive
