#!/usr/bin/env bash
# ____        _     _ _              ___  ____
#|  _ \  __ _| |__ | | | _____  ___ / _ \/ ___|     Stefan Dahlke
#| | | |/ _` | '_ \| | |/ / _ \/ __| | | \___ \     https://www.github.com/dahlkes
#| |_| | (_| | | | | |   <  __/\__ \ |_| |___) |
#|____/ \__,_|_| |_|_|_|\_\___||___/\___/|____/
#
# NAME: DahlkesOS
# DESC: A installation script for my personal ArchLinux setup.
# WARNING: Run this script at your own risk.

ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime
hwclock --systohc
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf
echo "KEYMAP=us" > /etc/vconsole.conf
read -p "What is the name of the system: " pc_name
echo $pc_name >> /etc/hostname
echo "127.0.0.1\tlocalhost" >> /etc/hosts
echo "::1\t\tlocalhost" >> /etc/hosts
echo "127.0.1.1\t$pc_name.localdomain $pc_name" >> /etc/hosts
systemctl enable NetworkManager
echo "The root password will now be set"
passwd
#pacman -S grub efibootmgr
grub-install --target=x86_64-efi --bootloader=GRUB --efi-directory=/efi --removable
grub-mkconfig -o /boot/grub/grub.cfg

# USER setup
useradd -m -G wheel -s /bin/zsh stefan
mount /dev/$
passwd stefan

line_number=$(grep -n "# %wheel ALL=(ALL:ALL) ALL" /etc/sudoers | cut -d ':' -f 1)

if [ ! -z "$line_number" ]; then
    sed -i "${line_number}s/^# //" /etc/sudoers
fi

read -p "I am ready." dummy
exit
