#!/usr/bin/env bash
# ____        _     _ _              ___  ____
#|  _ \  __ _| |__ | | | _____  ___ / _ \/ ___|     Stefan Dahlke
#| | | |/ _` | '_ \| | |/ / _ \/ __| | | \___ \     https://www.github.com/dahlkes
#| |_| | (_| | | | | |   <  __/\__ \ |_| |___) |
#|____/ \__,_|_| |_|_|_|\_\___||___/\___/|____/
#
# NAME: DahlkesOS
# DESC: A installation script for my personal ArchLinux setup.
# WARNING: Run this script at your own risk.

if [ -e /sys/firmware/efi/efivars ]; then
    is_uefi=true
else
    is_uefi=false
fi

fdisk -l

read -p "Which device to you want to partitionate? (input the whole device path /dev/sda) " device
cfdisk $device

mkfs.ext4 /dev/vda3

if $is_uefi == true; then
   mkfs.fat32 /dev/vda2
fi

swapon /dev/vda1

mount --mkdir /dev/vda3 /mnt
mount --mkdir /dev/vda2 /mnt/boot

pacstrap -K /mnt base linux linux-firmware vim git

genfstab -U /mnt >> /mnt/etc/fstab
cp configSystem /mnt/root
arch-chroot /mnt /bin/bash -c "bash /root/configSystem"
rm /mnt/root/configSystem
